apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.kafka.name }}
  namespace: {{ .Values.namespace }}
  labels:
  {{- include "kafkahelmdeploy.kafkalabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.kafka.type }}
  ports:
    - port: {{ .Values.service.kafka.port }}
      targetPort: {{ .Values.service.kafka.port }}
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.kafka.nodePort }}
  selector:
    {{- include "kafkahelmdeploy.kafkaselectors" . | nindent 4 }}
